### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by amitbha** [BasioMeusPuga/Lector#19]
1. Decrease the height of the status bar.
2. How to manage books? like group, star, etc. I can't find a way to make a priority reading list.
3. Smooth the mouse scrolling. It's too slow for epub.
4. Support continual reading mode.
5. Use filename as title insead of "Unknown".

**Comment by BasioMeusPuga** [comment]
1. I've added a 'Distraction free mode' that can be triggered with `Ctrl + D` or the statusbar button. It basically hides all the UI elements.
2. You can either put them in separate folders and tag those folder names. OR tag them with a "priority" etc tag. Ratings are a little low down on my TODO list, I'm afraid.
3. I don't understand. Is this different from the scroll / mouse sensitivity configured on your system? Because I haven't touched any Qt Widget setting here.
4. As in page followed by page in comic reading mode? That's coming.
5. Done in the last commit.

**Comment by amitbha** [comment]
Thanks for your reply and great job!
2. I want to pin some books at the top, which reminds me to finish them first. Tag can't help.
3. I increase the 'scroll lines' in qt5-config, and it's ok.
4. For pdf files, use only 'space' to turn to the next page.

**Comment by BasioMeusPuga** [comment]
2. This will have to wait. A 'Sort by rating' might be able to help, but like I said, that's still some way away. I can maybe implement something like giving the book a star that shows up on the list, but I don't see the point of that over just tagging a book / directory.

4. That's what it does now. If there's nothing left on the page, a spacebar press will take you to the next page.

I'm going to close this issue now. If you think there's anything else, don't hesitate to write.
