### ISSUE TITLE
Would it be possible to integrate this as a channel/plugin to plex (plex.tv?) 

### ISSUE THREAD

**Issue by gelsas** [BasioMeusPuga/Lector#36]
Would it be possible to integrate this as a channel/plugin to plex (plex.tv?) 

It would be the perfect thing for my plex server. It manages everything already tv shows/movies/music only ebook/comic support is missing.
Check this link aswell: https://forums.plex.tv/search?adv=&search=Ebook&title=&author=&cat=all&tags=&discussion_d=1&discussion_question=1&discussion_poll=1&comment_c=1&comment_answer=1&within=1+day&date=
Thousands of people would use it if it would be available as a plex plugin

Please let me know if it is possible and what would need to be done to add it to plex

**Comment by BasioMeusPuga** [comment]
Unlikely. Plex is closed source. Two, it doesn't offer a client that has "reader" functionality. That means that even if you were to write a plugin that pointed its way to the right books, Plex won't know what to do with them. Also, this is totally outside the scope of this project - which is to provide a desktop based ebook reader.

If someone can convince the Plex people to serve up those books over the network, like a server is expected to do, I'll see what I can do about being able to read them. Until then, you're better off with a network share if you want to use Lector.

**Comment by gelsas** [comment]
Alright thank you! Then I will use this seperatly from Plex. 
I just got one more question. Is it possible to directly send from that interface an ebook to my kindle ? - https://www.amazon.com/gp/sendtokindle

**Comment by BasioMeusPuga** [comment]
Sorry about the delay in replying. My laptop broke down something fierce.

About transferring files to your Kindle, it's doable, but I'd have to implement some kind of conversion routine first. This is because the Kindle doesn't support epub files. I'll think about it. But it will be quite low on the TODO list until I can get some more pressing things figured out first.

Two, you have to install this on your Laptop/Desktop and then you can read files on your NAS. You will have to mount the shared directory somewhere first, of course.

I hope this helps.
